// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbp1-DBShRkCAT1RQVaDSWzC5BM3ANLvQ',
    appId: '1:414678399045:android:0cac6ba2ba4e4d7e204b2c',
    messagingSenderId: '414678399045',
    projectId: 'mynotes-akz',
    storageBucket: 'mynotes-akz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqMLDEoKRp8qwalmKENejU0XdEiYIgGjg',
    appId: '1:414678399045:ios:e598e67b9be9f95a204b2c',
    messagingSenderId: '414678399045',
    projectId: 'mynotes-akz',
    storageBucket: 'mynotes-akz.appspot.com',
    iosClientId: '414678399045-k0qs914hrmm8hu7292l9hjh9ru535p7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotesVand',
  );
}
